name: "environment"

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      pick_runner:
        description: 'runner to use, dev or prod'
        default: 'manual'
        required: true
jobs:
  set_runner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.set_runner.outputs.runner }}
    steps:
      - id: set_runner
        run: |
          if [[ ${{ github.event.inputs.pick_runner }} == '' ]]; then
            echo "::set-output name=runner::automated"
          else
            echo "::set-output name=runner::${{ github.event.inputs.pick_runner }}" 
          fi 
  display_runner:
    runs-on: ubuntu-latest
    needs: set_runner
    steps:
      - run: echo ${{needs.set_runner.outputs.runner}}
