name: "environment"

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      pick_runner:
        description: 'runner to use, dev or prod'
        default: 'manual'
        required: true
jobs:
  set_runner:
    runs-on: ubuntu-latest
    steps:
    - id: set_runner
      run: |
        if [[ "Runner: ${{ github.event.inputs.pick_runner }}" == "Runner: " ]]; then
          echo "::set-output name=runner:dev"
        else
          echo "::set-output name=runner:${{ github.event.inputs.pick_runner }}"
        fi
    outputs:
      dest_runner: ${{steps.set_runner.outputs.runner}}

  display_runner:
    runs-on: ubuntu-latest
    needs: set_runner
    steps:
    - id: display_runner
      run: |
        echo "selected runner: ${{needs.set_runner.outputs.dest_runner}}"
        echo "Step complete"

