name: "environment"

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      pick_runner:
        description: 'runner to use, dev or prod'
        default: 'dev'
        required: true
jobs:
  set_runner:
    runs-on: ubuntu-latest 
    steps:
    - name: Set env runner
      run: |
        if [[ ${{ github.event.inputs.pick_runner }} == '' ]]; then
          echo "RUNNER=dev" >> $GITHUB_ENV
        else
          echo "RUNNER=${{ github.event.inputs.pick_runner }}" >> $GITHUB_ENV
        fi
    outputs:
      dest_runner: $RUNNER
      
  display_runner:
    runs-on: ubuntu-latest 
    needs: set_runner
    steps:
    - id: display_runner
      run: |
        echo "selected runner: ${{needs.set_runner.outputs.dest_runner}}"
        echo "Step complete"

