# bundle workflow

name: bundle-workflow

on:
  release:
    types:
      - created

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        id: set_env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: display
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}



