# bundle workflow

name: bundle-workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason for uploading media'
        default: 'manual execution'
        required: true

jobs:
  build:
    name: Create Release
    runs-on: ${{ matrix.os}}
    
    strategy:
     matrix:
      os: [ubuntu-18.04, ubuntu-20.04]
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        id: set_env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: display
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo ${{ matrix.os }}



