# bundle workflow

name: bundle-workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual input test: Reason for running this deployment?'
        default: 'pipeline testing'
        required: true

      pick_runner:
        description: 'runner to use, dev or prod'
        default: 'ubuntu-latest'
        required: true

  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        id: set_env
        run: echo ::set-env name=RELEASE_TAG::$(echo ${GITHUB_REF:10})
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: $RELEASE_TAG
          release_name: v1

