name: "Terraform"

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      pick_runner:
        description: 'runner to use, dev or prod'
        default: 'dev'
        required: true
jobs:
  set_runner:
    runs-on: ubuntu-latest 
    steps:
    - id: set_runner_automated
      run: echo "RUNNER=dev" >> $GITHUB_ENV

    - id: set_runner_manual
      if: ${{ github.event.inputs.pick_runner }} != ''
      run: echo "RUNNER=${{ github.event.inputs.pick_runner }}" >> $GITHUB_ENV
      
    outputs:
      dest_runner: $RUNNER
      

