name: "environment"

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      pick_runner:
        description: 'runner to use, dev or prod'
        default: 'manual'
        required: true
jobs:
  set_runner_manual:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.pick_runner }}
    outputs:
      runner: ${{ steps.set_runner_manual.outputs.runner }}
    steps:
      - id: set_runner_manual
        run: echo "::set-output name=runner::${{ github.event.inputs.pick_runner }}" 
          
  set_runner_automated:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.set_runner_automated.outputs.runner }}
    steps:
      - id: set_runner_automated
        run: echo "::set-output name=runner::automated" 
          
  set_runner:
    runs-on: ubuntu-latest
    needs: [set_runner_automated, set_runner_manual]
    if: ${{ always() }}

    steps:
      - id: set_runner
        run: |
          echo "Runners:${{needs.set_runner_automated.outputs.runner}} ${{needs.set_runner_automated.outputs.runner}}"
          if [[ "Runners: ${{needs.set_runner_manual.outputs.runner}}" == "Runners: " ]]; then
            echo "::set-output name=runner:dev"
            echo "Automated: dev"
          else
            echo "::set-output name=runner:${{ github.event.inputs.pick_runner }}"
            echo "Manual: ${{ github.event.inputs.pick_runner }}"
          fi

